version: "3.8"

services:

  postgres-db:
    container_name: postgres_DB
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dataBase
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      python_prod_net:
        ipv4_address: 173.16.100.11

  webflask:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ".:/code"
    environment:
      FLASK_ENV: "development"
    depends_on:
      - postgres-db
    networks:
      python_prod_net:
        ipv4_address: 173.16.100.12

networks:
  python_prod_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.16.100.0/24
